language: go

go:
  - 1.5
  - 1.6

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/tools/godep

install:
  - go install -race -v std

script:
  - $HOME/gopath/bin/golint .
  - make test
  - make coveralls
